import pygame

bg_menu_image = pygame.image.load('assets/images/menu_bg.jpg')
bg_dificuldade_image = pygame.image.load('assets/images/dificuldade_menu.png')
iniciar_on = pygame.image.load('assets/images/iniciar_on.png')
iniciar_off = pygame.image.load('assets/images/iniciar_off.png')
dificuldade_on = pygame.image.load('assets/images/dificuldade_on.png')
dificuldade_off = pygame.image.load('assets/images/dificuldade_off.png')
ranking_on = pygame.image.load('assets/images/ranking_on.png')
sair_on = pygame.image.load('assets/images/sair_on.png')
facil_on = pygame.image.load('assets/images/facil_on.png')
medio_on = pygame.image.load('assets/images/medio_on.png')
dificil_on = pygame.image.load('assets/images/dificil_on.png')
voltar_on = pygame.image.load('assets/images/voltar_on.png')
alien = pygame.image.load("assets/images/alien1.png")
bg = pygame.image.load("assets/images/bg.png")
spaceship = pygame.image.load("assets/images/ship_4.png")
bullet = pygame.image.load("assets/images/shot.png")